server:
  name: "chains-sso"
  port: ":8000"
  base_path: "/api/v1"
  test_mode: true

logger:
  level: "debug"
  format: "text"

database:
  sql:
    url: "postgresql://postgres:postgres@db:7000/postgres?sslmode=disable"

jwt:
  user:
    access_token:
      secret_key: "UnG06MAU2i1Mvqf8" #example
      token_lifetime: 900
  service:
    secret_key: "H6eHCV0rKzJIAEVE" #example

swagger:
  enabled: true
  url: "/swagger"
  port: "8080"

services:
  sso-svc:
    addresses: "localhost:8001"
  elector-cab-svc:
    addresses: "localhost:8002"