/*
Chains API

Chains API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateProfileByAdmin type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProfileByAdmin{}

// UpdateProfileByAdmin struct for UpdateProfileByAdmin
type UpdateProfileByAdmin struct {
	Data UpdateProfileByAdminData `json:"data"`
}

type _UpdateProfileByAdmin UpdateProfileByAdmin

// NewUpdateProfileByAdmin instantiates a new UpdateProfileByAdmin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProfileByAdmin(data UpdateProfileByAdminData) *UpdateProfileByAdmin {
	this := UpdateProfileByAdmin{}
	this.Data = data
	return &this
}

// NewUpdateProfileByAdminWithDefaults instantiates a new UpdateProfileByAdmin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProfileByAdminWithDefaults() *UpdateProfileByAdmin {
	this := UpdateProfileByAdmin{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateProfileByAdmin) GetData() UpdateProfileByAdminData {
	if o == nil {
		var ret UpdateProfileByAdminData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateProfileByAdmin) GetDataOk() (*UpdateProfileByAdminData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateProfileByAdmin) SetData(v UpdateProfileByAdminData) {
	o.Data = v
}

func (o UpdateProfileByAdmin) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProfileByAdmin) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateProfileByAdmin) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateProfileByAdmin := _UpdateProfileByAdmin{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateProfileByAdmin)

	if err != nil {
		return err
	}

	*o = UpdateProfileByAdmin(varUpdateProfileByAdmin)

	return err
}

type NullableUpdateProfileByAdmin struct {
	value *UpdateProfileByAdmin
	isSet bool
}

func (v NullableUpdateProfileByAdmin) Get() *UpdateProfileByAdmin {
	return v.value
}

func (v *NullableUpdateProfileByAdmin) Set(val *UpdateProfileByAdmin) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProfileByAdmin) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProfileByAdmin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProfileByAdmin(val *UpdateProfileByAdmin) *NullableUpdateProfileByAdmin {
	return &NullableUpdateProfileByAdmin{value: val, isSet: true}
}

func (v NullableUpdateProfileByAdmin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProfileByAdmin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


