/*
Chains API

Chains API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CabinetData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CabinetData{}

// CabinetData struct for CabinetData
type CabinetData struct {
	// User ID of the elector.
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes CabinetAttributes `json:"attributes"`
}

type _CabinetData CabinetData

// NewCabinetData instantiates a new CabinetData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCabinetData(id string, type_ string, attributes CabinetAttributes) *CabinetData {
	this := CabinetData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCabinetDataWithDefaults instantiates a new CabinetData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCabinetDataWithDefaults() *CabinetData {
	this := CabinetData{}
	return &this
}

// GetId returns the Id field value
func (o *CabinetData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CabinetData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CabinetData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *CabinetData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CabinetData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CabinetData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CabinetData) GetAttributes() CabinetAttributes {
	if o == nil {
		var ret CabinetAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CabinetData) GetAttributesOk() (*CabinetAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CabinetData) SetAttributes(v CabinetAttributes) {
	o.Attributes = v
}

func (o CabinetData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CabinetData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CabinetData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCabinetData := _CabinetData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCabinetData)

	if err != nil {
		return err
	}

	*o = CabinetData(varCabinetData)

	return err
}

type NullableCabinetData struct {
	value *CabinetData
	isSet bool
}

func (v NullableCabinetData) Get() *CabinetData {
	return v.value
}

func (v *NullableCabinetData) Set(val *CabinetData) {
	v.value = val
	v.isSet = true
}

func (v NullableCabinetData) IsSet() bool {
	return v.isSet
}

func (v *NullableCabinetData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCabinetData(val *CabinetData) *NullableCabinetData {
	return &NullableCabinetData{value: val, isSet: true}
}

func (v NullableCabinetData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCabinetData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


