/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
)

// checks if the JobResumeAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobResumeAttributes{}

// JobResumeAttributes struct for JobResumeAttributes
type JobResumeAttributes struct {
	// elector degree
	Degree *string `json:"degree,omitempty"`
	// elector industry
	Industry *string `json:"industry,omitempty"`
	// elector income
	Income *string `json:"income,omitempty"`
	// The date and time when the degree was last updated.
	DegreeUpdatedAt *time.Time `json:"degree_updated_at,omitempty"`
	// The date and time when the industry was last updated.
	IndustryUpdatedAt *time.Time `json:"industry_updated_at,omitempty"`
	// The date and time when the income was last updated.
	IncomeUpdatedAt *time.Time `json:"income_updated_at,omitempty"`
}

// NewJobResumeAttributes instantiates a new JobResumeAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobResumeAttributes() *JobResumeAttributes {
	this := JobResumeAttributes{}
	return &this
}

// NewJobResumeAttributesWithDefaults instantiates a new JobResumeAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobResumeAttributesWithDefaults() *JobResumeAttributes {
	this := JobResumeAttributes{}
	return &this
}

// GetDegree returns the Degree field value if set, zero value otherwise.
func (o *JobResumeAttributes) GetDegree() string {
	if o == nil || IsNil(o.Degree) {
		var ret string
		return ret
	}
	return *o.Degree
}

// GetDegreeOk returns a tuple with the Degree field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobResumeAttributes) GetDegreeOk() (*string, bool) {
	if o == nil || IsNil(o.Degree) {
		return nil, false
	}
	return o.Degree, true
}

// HasDegree returns a boolean if a field has been set.
func (o *JobResumeAttributes) HasDegree() bool {
	if o != nil && !IsNil(o.Degree) {
		return true
	}

	return false
}

// SetDegree gets a reference to the given string and assigns it to the Degree field.
func (o *JobResumeAttributes) SetDegree(v string) {
	o.Degree = &v
}

// GetIndustry returns the Industry field value if set, zero value otherwise.
func (o *JobResumeAttributes) GetIndustry() string {
	if o == nil || IsNil(o.Industry) {
		var ret string
		return ret
	}
	return *o.Industry
}

// GetIndustryOk returns a tuple with the Industry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobResumeAttributes) GetIndustryOk() (*string, bool) {
	if o == nil || IsNil(o.Industry) {
		return nil, false
	}
	return o.Industry, true
}

// HasIndustry returns a boolean if a field has been set.
func (o *JobResumeAttributes) HasIndustry() bool {
	if o != nil && !IsNil(o.Industry) {
		return true
	}

	return false
}

// SetIndustry gets a reference to the given string and assigns it to the Industry field.
func (o *JobResumeAttributes) SetIndustry(v string) {
	o.Industry = &v
}

// GetIncome returns the Income field value if set, zero value otherwise.
func (o *JobResumeAttributes) GetIncome() string {
	if o == nil || IsNil(o.Income) {
		var ret string
		return ret
	}
	return *o.Income
}

// GetIncomeOk returns a tuple with the Income field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobResumeAttributes) GetIncomeOk() (*string, bool) {
	if o == nil || IsNil(o.Income) {
		return nil, false
	}
	return o.Income, true
}

// HasIncome returns a boolean if a field has been set.
func (o *JobResumeAttributes) HasIncome() bool {
	if o != nil && !IsNil(o.Income) {
		return true
	}

	return false
}

// SetIncome gets a reference to the given string and assigns it to the Income field.
func (o *JobResumeAttributes) SetIncome(v string) {
	o.Income = &v
}

// GetDegreeUpdatedAt returns the DegreeUpdatedAt field value if set, zero value otherwise.
func (o *JobResumeAttributes) GetDegreeUpdatedAt() time.Time {
	if o == nil || IsNil(o.DegreeUpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.DegreeUpdatedAt
}

// GetDegreeUpdatedAtOk returns a tuple with the DegreeUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobResumeAttributes) GetDegreeUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DegreeUpdatedAt) {
		return nil, false
	}
	return o.DegreeUpdatedAt, true
}

// HasDegreeUpdatedAt returns a boolean if a field has been set.
func (o *JobResumeAttributes) HasDegreeUpdatedAt() bool {
	if o != nil && !IsNil(o.DegreeUpdatedAt) {
		return true
	}

	return false
}

// SetDegreeUpdatedAt gets a reference to the given time.Time and assigns it to the DegreeUpdatedAt field.
func (o *JobResumeAttributes) SetDegreeUpdatedAt(v time.Time) {
	o.DegreeUpdatedAt = &v
}

// GetIndustryUpdatedAt returns the IndustryUpdatedAt field value if set, zero value otherwise.
func (o *JobResumeAttributes) GetIndustryUpdatedAt() time.Time {
	if o == nil || IsNil(o.IndustryUpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.IndustryUpdatedAt
}

// GetIndustryUpdatedAtOk returns a tuple with the IndustryUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobResumeAttributes) GetIndustryUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.IndustryUpdatedAt) {
		return nil, false
	}
	return o.IndustryUpdatedAt, true
}

// HasIndustryUpdatedAt returns a boolean if a field has been set.
func (o *JobResumeAttributes) HasIndustryUpdatedAt() bool {
	if o != nil && !IsNil(o.IndustryUpdatedAt) {
		return true
	}

	return false
}

// SetIndustryUpdatedAt gets a reference to the given time.Time and assigns it to the IndustryUpdatedAt field.
func (o *JobResumeAttributes) SetIndustryUpdatedAt(v time.Time) {
	o.IndustryUpdatedAt = &v
}

// GetIncomeUpdatedAt returns the IncomeUpdatedAt field value if set, zero value otherwise.
func (o *JobResumeAttributes) GetIncomeUpdatedAt() time.Time {
	if o == nil || IsNil(o.IncomeUpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.IncomeUpdatedAt
}

// GetIncomeUpdatedAtOk returns a tuple with the IncomeUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobResumeAttributes) GetIncomeUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.IncomeUpdatedAt) {
		return nil, false
	}
	return o.IncomeUpdatedAt, true
}

// HasIncomeUpdatedAt returns a boolean if a field has been set.
func (o *JobResumeAttributes) HasIncomeUpdatedAt() bool {
	if o != nil && !IsNil(o.IncomeUpdatedAt) {
		return true
	}

	return false
}

// SetIncomeUpdatedAt gets a reference to the given time.Time and assigns it to the IncomeUpdatedAt field.
func (o *JobResumeAttributes) SetIncomeUpdatedAt(v time.Time) {
	o.IncomeUpdatedAt = &v
}

func (o JobResumeAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobResumeAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Degree) {
		toSerialize["degree"] = o.Degree
	}
	if !IsNil(o.Industry) {
		toSerialize["industry"] = o.Industry
	}
	if !IsNil(o.Income) {
		toSerialize["income"] = o.Income
	}
	if !IsNil(o.DegreeUpdatedAt) {
		toSerialize["degree_updated_at"] = o.DegreeUpdatedAt
	}
	if !IsNil(o.IndustryUpdatedAt) {
		toSerialize["industry_updated_at"] = o.IndustryUpdatedAt
	}
	if !IsNil(o.IncomeUpdatedAt) {
		toSerialize["income_updated_at"] = o.IncomeUpdatedAt
	}
	return toSerialize, nil
}

type NullableJobResumeAttributes struct {
	value *JobResumeAttributes
	isSet bool
}

func (v NullableJobResumeAttributes) Get() *JobResumeAttributes {
	return v.value
}

func (v *NullableJobResumeAttributes) Set(val *JobResumeAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableJobResumeAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableJobResumeAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobResumeAttributes(val *JobResumeAttributes) *NullableJobResumeAttributes {
	return &NullableJobResumeAttributes{value: val, isSet: true}
}

func (v NullableJobResumeAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobResumeAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


