/*
Chains API

Chains API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOwnProfileData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOwnProfileData{}

// CreateOwnProfileData struct for CreateOwnProfileData
type CreateOwnProfileData struct {
	// User ID of the elector.
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes CreateOwnProfileDataAttributes `json:"attributes"`
}

type _CreateOwnProfileData CreateOwnProfileData

// NewCreateOwnProfileData instantiates a new CreateOwnProfileData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOwnProfileData(id string, type_ string, attributes CreateOwnProfileDataAttributes) *CreateOwnProfileData {
	this := CreateOwnProfileData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateOwnProfileDataWithDefaults instantiates a new CreateOwnProfileData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOwnProfileDataWithDefaults() *CreateOwnProfileData {
	this := CreateOwnProfileData{}
	return &this
}

// GetId returns the Id field value
func (o *CreateOwnProfileData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateOwnProfileData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateOwnProfileData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *CreateOwnProfileData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateOwnProfileData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateOwnProfileData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateOwnProfileData) GetAttributes() CreateOwnProfileDataAttributes {
	if o == nil {
		var ret CreateOwnProfileDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateOwnProfileData) GetAttributesOk() (*CreateOwnProfileDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateOwnProfileData) SetAttributes(v CreateOwnProfileDataAttributes) {
	o.Attributes = v
}

func (o CreateOwnProfileData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOwnProfileData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateOwnProfileData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOwnProfileData := _CreateOwnProfileData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOwnProfileData)

	if err != nil {
		return err
	}

	*o = CreateOwnProfileData(varCreateOwnProfileData)

	return err
}

type NullableCreateOwnProfileData struct {
	value *CreateOwnProfileData
	isSet bool
}

func (v NullableCreateOwnProfileData) Get() *CreateOwnProfileData {
	return v.value
}

func (v *NullableCreateOwnProfileData) Set(val *CreateOwnProfileData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOwnProfileData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOwnProfileData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOwnProfileData(val *CreateOwnProfileData) *NullableCreateOwnProfileData {
	return &NullableCreateOwnProfileData{value: val, isSet: true}
}

func (v NullableCreateOwnProfileData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOwnProfileData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


