/*
Chains API

Chains API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateUserByAdminData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUserByAdminData{}

// CreateUserByAdminData struct for CreateUserByAdminData
type CreateUserByAdminData struct {
	Type string `json:"type"`
	Attributes CreateUserByAdminDataAttributes `json:"attributes"`
}

type _CreateUserByAdminData CreateUserByAdminData

// NewCreateUserByAdminData instantiates a new CreateUserByAdminData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUserByAdminData(type_ string, attributes CreateUserByAdminDataAttributes) *CreateUserByAdminData {
	this := CreateUserByAdminData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateUserByAdminDataWithDefaults instantiates a new CreateUserByAdminData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUserByAdminDataWithDefaults() *CreateUserByAdminData {
	this := CreateUserByAdminData{}
	return &this
}

// GetType returns the Type field value
func (o *CreateUserByAdminData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateUserByAdminData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateUserByAdminData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateUserByAdminData) GetAttributes() CreateUserByAdminDataAttributes {
	if o == nil {
		var ret CreateUserByAdminDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateUserByAdminData) GetAttributesOk() (*CreateUserByAdminDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateUserByAdminData) SetAttributes(v CreateUserByAdminDataAttributes) {
	o.Attributes = v
}

func (o CreateUserByAdminData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUserByAdminData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateUserByAdminData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateUserByAdminData := _CreateUserByAdminData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateUserByAdminData)

	if err != nil {
		return err
	}

	*o = CreateUserByAdminData(varCreateUserByAdminData)

	return err
}

type NullableCreateUserByAdminData struct {
	value *CreateUserByAdminData
	isSet bool
}

func (v NullableCreateUserByAdminData) Get() *CreateUserByAdminData {
	return v.value
}

func (v *NullableCreateUserByAdminData) Set(val *CreateUserByAdminData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUserByAdminData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUserByAdminData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUserByAdminData(val *CreateUserByAdminData) *NullableCreateUserByAdminData {
	return &NullableCreateUserByAdminData{value: val, isSet: true}
}

func (v NullableCreateUserByAdminData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUserByAdminData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


