/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateOwnProfileDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOwnProfileDataAttributes{}

// UpdateOwnProfileDataAttributes struct for UpdateOwnProfileDataAttributes
type UpdateOwnProfileDataAttributes struct {
	// The username of the elector.
	Username *string `json:"username,omitempty"`
	// The pseudonym of the elector.
	Pseudonym *string `json:"pseudonym,omitempty"`
	// A brief description of the elector.
	Description *string `json:"description,omitempty"`
	// The URL of the elector's avatar image.
	Avatar *string `json:"avatar,omitempty"`
}

// NewUpdateOwnProfileDataAttributes instantiates a new UpdateOwnProfileDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOwnProfileDataAttributes() *UpdateOwnProfileDataAttributes {
	this := UpdateOwnProfileDataAttributes{}
	return &this
}

// NewUpdateOwnProfileDataAttributesWithDefaults instantiates a new UpdateOwnProfileDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOwnProfileDataAttributesWithDefaults() *UpdateOwnProfileDataAttributes {
	this := UpdateOwnProfileDataAttributes{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *UpdateOwnProfileDataAttributes) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOwnProfileDataAttributes) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *UpdateOwnProfileDataAttributes) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *UpdateOwnProfileDataAttributes) SetUsername(v string) {
	o.Username = &v
}

// GetPseudonym returns the Pseudonym field value if set, zero value otherwise.
func (o *UpdateOwnProfileDataAttributes) GetPseudonym() string {
	if o == nil || IsNil(o.Pseudonym) {
		var ret string
		return ret
	}
	return *o.Pseudonym
}

// GetPseudonymOk returns a tuple with the Pseudonym field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOwnProfileDataAttributes) GetPseudonymOk() (*string, bool) {
	if o == nil || IsNil(o.Pseudonym) {
		return nil, false
	}
	return o.Pseudonym, true
}

// HasPseudonym returns a boolean if a field has been set.
func (o *UpdateOwnProfileDataAttributes) HasPseudonym() bool {
	if o != nil && !IsNil(o.Pseudonym) {
		return true
	}

	return false
}

// SetPseudonym gets a reference to the given string and assigns it to the Pseudonym field.
func (o *UpdateOwnProfileDataAttributes) SetPseudonym(v string) {
	o.Pseudonym = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateOwnProfileDataAttributes) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOwnProfileDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateOwnProfileDataAttributes) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateOwnProfileDataAttributes) SetDescription(v string) {
	o.Description = &v
}

// GetAvatar returns the Avatar field value if set, zero value otherwise.
func (o *UpdateOwnProfileDataAttributes) GetAvatar() string {
	if o == nil || IsNil(o.Avatar) {
		var ret string
		return ret
	}
	return *o.Avatar
}

// GetAvatarOk returns a tuple with the Avatar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOwnProfileDataAttributes) GetAvatarOk() (*string, bool) {
	if o == nil || IsNil(o.Avatar) {
		return nil, false
	}
	return o.Avatar, true
}

// HasAvatar returns a boolean if a field has been set.
func (o *UpdateOwnProfileDataAttributes) HasAvatar() bool {
	if o != nil && !IsNil(o.Avatar) {
		return true
	}

	return false
}

// SetAvatar gets a reference to the given string and assigns it to the Avatar field.
func (o *UpdateOwnProfileDataAttributes) SetAvatar(v string) {
	o.Avatar = &v
}

func (o UpdateOwnProfileDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOwnProfileDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Pseudonym) {
		toSerialize["pseudonym"] = o.Pseudonym
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Avatar) {
		toSerialize["avatar"] = o.Avatar
	}
	return toSerialize, nil
}

type NullableUpdateOwnProfileDataAttributes struct {
	value *UpdateOwnProfileDataAttributes
	isSet bool
}

func (v NullableUpdateOwnProfileDataAttributes) Get() *UpdateOwnProfileDataAttributes {
	return v.value
}

func (v *NullableUpdateOwnProfileDataAttributes) Set(val *UpdateOwnProfileDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOwnProfileDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOwnProfileDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOwnProfileDataAttributes(val *UpdateOwnProfileDataAttributes) *NullableUpdateOwnProfileDataAttributes {
	return &NullableUpdateOwnProfileDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateOwnProfileDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOwnProfileDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


