/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobResume type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobResume{}

// JobResume struct for JobResume
type JobResume struct {
	Data JobResumeData `json:"data"`
}

type _JobResume JobResume

// NewJobResume instantiates a new JobResume object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobResume(data JobResumeData) *JobResume {
	this := JobResume{}
	this.Data = data
	return &this
}

// NewJobResumeWithDefaults instantiates a new JobResume object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobResumeWithDefaults() *JobResume {
	this := JobResume{}
	return &this
}

// GetData returns the Data field value
func (o *JobResume) GetData() JobResumeData {
	if o == nil {
		var ret JobResumeData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *JobResume) GetDataOk() (*JobResumeData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *JobResume) SetData(v JobResumeData) {
	o.Data = v
}

func (o JobResume) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobResume) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *JobResume) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobResume := _JobResume{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobResume)

	if err != nil {
		return err
	}

	*o = JobResume(varJobResume)

	return err
}

type NullableJobResume struct {
	value *JobResume
	isSet bool
}

func (v NullableJobResume) Get() *JobResume {
	return v.value
}

func (v *NullableJobResume) Set(val *JobResume) {
	v.value = val
	v.isSet = true
}

func (v NullableJobResume) IsSet() bool {
	return v.isSet
}

func (v *NullableJobResume) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobResume(val *JobResume) *NullableJobResume {
	return &NullableJobResume{value: val, isSet: true}
}

func (v NullableJobResume) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobResume) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


