/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobResumeData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobResumeData{}

// JobResumeData struct for JobResumeData
type JobResumeData struct {
	// User ID of the elector.
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes JobResumeAttributes `json:"attributes"`
}

type _JobResumeData JobResumeData

// NewJobResumeData instantiates a new JobResumeData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobResumeData(id string, type_ string, attributes JobResumeAttributes) *JobResumeData {
	this := JobResumeData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewJobResumeDataWithDefaults instantiates a new JobResumeData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobResumeDataWithDefaults() *JobResumeData {
	this := JobResumeData{}
	return &this
}

// GetId returns the Id field value
func (o *JobResumeData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *JobResumeData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *JobResumeData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *JobResumeData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *JobResumeData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *JobResumeData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *JobResumeData) GetAttributes() JobResumeAttributes {
	if o == nil {
		var ret JobResumeAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *JobResumeData) GetAttributesOk() (*JobResumeAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *JobResumeData) SetAttributes(v JobResumeAttributes) {
	o.Attributes = v
}

func (o JobResumeData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobResumeData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *JobResumeData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobResumeData := _JobResumeData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobResumeData)

	if err != nil {
		return err
	}

	*o = JobResumeData(varJobResumeData)

	return err
}

type NullableJobResumeData struct {
	value *JobResumeData
	isSet bool
}

func (v NullableJobResumeData) Get() *JobResumeData {
	return v.value
}

func (v *NullableJobResumeData) Set(val *JobResumeData) {
	v.value = val
	v.isSet = true
}

func (v NullableJobResumeData) IsSet() bool {
	return v.isSet
}

func (v *NullableJobResumeData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobResumeData(val *JobResumeData) *NullableJobResumeData {
	return &NullableJobResumeData{value: val, isSet: true}
}

func (v NullableJobResumeData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobResumeData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


