/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOwnProfileDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOwnProfileDataAttributes{}

// CreateOwnProfileDataAttributes struct for CreateOwnProfileDataAttributes
type CreateOwnProfileDataAttributes struct {
	// The username of the elector.
	Username string `json:"username"`
	// The pseudonym of the elector.
	Pseudonym *string `json:"pseudonym,omitempty"`
	// A brief description of the elector.
	Description *string `json:"description,omitempty"`
	// The URL of the elector's avatar image.
	Avatar *string `json:"avatar,omitempty"`
}

type _CreateOwnProfileDataAttributes CreateOwnProfileDataAttributes

// NewCreateOwnProfileDataAttributes instantiates a new CreateOwnProfileDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOwnProfileDataAttributes(username string) *CreateOwnProfileDataAttributes {
	this := CreateOwnProfileDataAttributes{}
	this.Username = username
	return &this
}

// NewCreateOwnProfileDataAttributesWithDefaults instantiates a new CreateOwnProfileDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOwnProfileDataAttributesWithDefaults() *CreateOwnProfileDataAttributes {
	this := CreateOwnProfileDataAttributes{}
	return &this
}

// GetUsername returns the Username field value
func (o *CreateOwnProfileDataAttributes) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *CreateOwnProfileDataAttributes) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *CreateOwnProfileDataAttributes) SetUsername(v string) {
	o.Username = v
}

// GetPseudonym returns the Pseudonym field value if set, zero value otherwise.
func (o *CreateOwnProfileDataAttributes) GetPseudonym() string {
	if o == nil || IsNil(o.Pseudonym) {
		var ret string
		return ret
	}
	return *o.Pseudonym
}

// GetPseudonymOk returns a tuple with the Pseudonym field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOwnProfileDataAttributes) GetPseudonymOk() (*string, bool) {
	if o == nil || IsNil(o.Pseudonym) {
		return nil, false
	}
	return o.Pseudonym, true
}

// HasPseudonym returns a boolean if a field has been set.
func (o *CreateOwnProfileDataAttributes) HasPseudonym() bool {
	if o != nil && !IsNil(o.Pseudonym) {
		return true
	}

	return false
}

// SetPseudonym gets a reference to the given string and assigns it to the Pseudonym field.
func (o *CreateOwnProfileDataAttributes) SetPseudonym(v string) {
	o.Pseudonym = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateOwnProfileDataAttributes) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOwnProfileDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateOwnProfileDataAttributes) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateOwnProfileDataAttributes) SetDescription(v string) {
	o.Description = &v
}

// GetAvatar returns the Avatar field value if set, zero value otherwise.
func (o *CreateOwnProfileDataAttributes) GetAvatar() string {
	if o == nil || IsNil(o.Avatar) {
		var ret string
		return ret
	}
	return *o.Avatar
}

// GetAvatarOk returns a tuple with the Avatar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOwnProfileDataAttributes) GetAvatarOk() (*string, bool) {
	if o == nil || IsNil(o.Avatar) {
		return nil, false
	}
	return o.Avatar, true
}

// HasAvatar returns a boolean if a field has been set.
func (o *CreateOwnProfileDataAttributes) HasAvatar() bool {
	if o != nil && !IsNil(o.Avatar) {
		return true
	}

	return false
}

// SetAvatar gets a reference to the given string and assigns it to the Avatar field.
func (o *CreateOwnProfileDataAttributes) SetAvatar(v string) {
	o.Avatar = &v
}

func (o CreateOwnProfileDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOwnProfileDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	if !IsNil(o.Pseudonym) {
		toSerialize["pseudonym"] = o.Pseudonym
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Avatar) {
		toSerialize["avatar"] = o.Avatar
	}
	return toSerialize, nil
}

func (o *CreateOwnProfileDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOwnProfileDataAttributes := _CreateOwnProfileDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOwnProfileDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateOwnProfileDataAttributes(varCreateOwnProfileDataAttributes)

	return err
}

type NullableCreateOwnProfileDataAttributes struct {
	value *CreateOwnProfileDataAttributes
	isSet bool
}

func (v NullableCreateOwnProfileDataAttributes) Get() *CreateOwnProfileDataAttributes {
	return v.value
}

func (v *NullableCreateOwnProfileDataAttributes) Set(val *CreateOwnProfileDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOwnProfileDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOwnProfileDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOwnProfileDataAttributes(val *CreateOwnProfileDataAttributes) *NullableCreateOwnProfileDataAttributes {
	return &NullableCreateOwnProfileDataAttributes{value: val, isSet: true}
}

func (v NullableCreateOwnProfileDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOwnProfileDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


