/*
Chains API

Chains API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateUserByAdmin type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUserByAdmin{}

// CreateUserByAdmin struct for CreateUserByAdmin
type CreateUserByAdmin struct {
	Data CreateUserByAdminData `json:"data"`
}

type _CreateUserByAdmin CreateUserByAdmin

// NewCreateUserByAdmin instantiates a new CreateUserByAdmin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUserByAdmin(data CreateUserByAdminData) *CreateUserByAdmin {
	this := CreateUserByAdmin{}
	this.Data = data
	return &this
}

// NewCreateUserByAdminWithDefaults instantiates a new CreateUserByAdmin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUserByAdminWithDefaults() *CreateUserByAdmin {
	this := CreateUserByAdmin{}
	return &this
}

// GetData returns the Data field value
func (o *CreateUserByAdmin) GetData() CreateUserByAdminData {
	if o == nil {
		var ret CreateUserByAdminData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateUserByAdmin) GetDataOk() (*CreateUserByAdminData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateUserByAdmin) SetData(v CreateUserByAdminData) {
	o.Data = v
}

func (o CreateUserByAdmin) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUserByAdmin) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateUserByAdmin) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateUserByAdmin := _CreateUserByAdmin{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateUserByAdmin)

	if err != nil {
		return err
	}

	*o = CreateUserByAdmin(varCreateUserByAdmin)

	return err
}

type NullableCreateUserByAdmin struct {
	value *CreateUserByAdmin
	isSet bool
}

func (v NullableCreateUserByAdmin) Get() *CreateUserByAdmin {
	return v.value
}

func (v *NullableCreateUserByAdmin) Set(val *CreateUserByAdmin) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUserByAdmin) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUserByAdmin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUserByAdmin(val *CreateUserByAdmin) *NullableCreateUserByAdmin {
	return &NullableCreateUserByAdmin{value: val, isSet: true}
}

func (v NullableCreateUserByAdmin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUserByAdmin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


