/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateOwnProfileData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOwnProfileData{}

// UpdateOwnProfileData struct for UpdateOwnProfileData
type UpdateOwnProfileData struct {
	// User ID of the elector.
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes UpdateOwnProfileDataAttributes `json:"attributes"`
}

type _UpdateOwnProfileData UpdateOwnProfileData

// NewUpdateOwnProfileData instantiates a new UpdateOwnProfileData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOwnProfileData(id string, type_ string, attributes UpdateOwnProfileDataAttributes) *UpdateOwnProfileData {
	this := UpdateOwnProfileData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateOwnProfileDataWithDefaults instantiates a new UpdateOwnProfileData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOwnProfileDataWithDefaults() *UpdateOwnProfileData {
	this := UpdateOwnProfileData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateOwnProfileData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateOwnProfileData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateOwnProfileData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateOwnProfileData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateOwnProfileData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateOwnProfileData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateOwnProfileData) GetAttributes() UpdateOwnProfileDataAttributes {
	if o == nil {
		var ret UpdateOwnProfileDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateOwnProfileData) GetAttributesOk() (*UpdateOwnProfileDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateOwnProfileData) SetAttributes(v UpdateOwnProfileDataAttributes) {
	o.Attributes = v
}

func (o UpdateOwnProfileData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOwnProfileData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateOwnProfileData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOwnProfileData := _UpdateOwnProfileData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOwnProfileData)

	if err != nil {
		return err
	}

	*o = UpdateOwnProfileData(varUpdateOwnProfileData)

	return err
}

type NullableUpdateOwnProfileData struct {
	value *UpdateOwnProfileData
	isSet bool
}

func (v NullableUpdateOwnProfileData) Get() *UpdateOwnProfileData {
	return v.value
}

func (v *NullableUpdateOwnProfileData) Set(val *UpdateOwnProfileData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOwnProfileData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOwnProfileData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOwnProfileData(val *UpdateOwnProfileData) *NullableUpdateOwnProfileData {
	return &NullableUpdateOwnProfileData{value: val, isSet: true}
}

func (v NullableUpdateOwnProfileData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOwnProfileData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


