/*
Chains API

Chains API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateUserByAdminDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUserByAdminDataAttributes{}

// CreateUserByAdminDataAttributes struct for CreateUserByAdminDataAttributes
type CreateUserByAdminDataAttributes struct {
	// The email address of the admin to be created.
	Email string `json:"email"`
	// The role of the admin to be created.
	Role string `json:"role"`
}

type _CreateUserByAdminDataAttributes CreateUserByAdminDataAttributes

// NewCreateUserByAdminDataAttributes instantiates a new CreateUserByAdminDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUserByAdminDataAttributes(email string, role string) *CreateUserByAdminDataAttributes {
	this := CreateUserByAdminDataAttributes{}
	this.Email = email
	this.Role = role
	return &this
}

// NewCreateUserByAdminDataAttributesWithDefaults instantiates a new CreateUserByAdminDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUserByAdminDataAttributesWithDefaults() *CreateUserByAdminDataAttributes {
	this := CreateUserByAdminDataAttributes{}
	return &this
}

// GetEmail returns the Email field value
func (o *CreateUserByAdminDataAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *CreateUserByAdminDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *CreateUserByAdminDataAttributes) SetEmail(v string) {
	o.Email = v
}

// GetRole returns the Role field value
func (o *CreateUserByAdminDataAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *CreateUserByAdminDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *CreateUserByAdminDataAttributes) SetRole(v string) {
	o.Role = v
}

func (o CreateUserByAdminDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUserByAdminDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *CreateUserByAdminDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateUserByAdminDataAttributes := _CreateUserByAdminDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateUserByAdminDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateUserByAdminDataAttributes(varCreateUserByAdminDataAttributes)

	return err
}

type NullableCreateUserByAdminDataAttributes struct {
	value *CreateUserByAdminDataAttributes
	isSet bool
}

func (v NullableCreateUserByAdminDataAttributes) Get() *CreateUserByAdminDataAttributes {
	return v.value
}

func (v *NullableCreateUserByAdminDataAttributes) Set(val *CreateUserByAdminDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUserByAdminDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUserByAdminDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUserByAdminDataAttributes(val *CreateUserByAdminDataAttributes) *NullableCreateUserByAdminDataAttributes {
	return &NullableCreateUserByAdminDataAttributes{value: val, isSet: true}
}

func (v NullableCreateUserByAdminDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUserByAdminDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


