/*
Chains API

Chains API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Cabinet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Cabinet{}

// Cabinet struct for Cabinet
type Cabinet struct {
	Data CabinetData `json:"data"`
}

type _Cabinet Cabinet

// NewCabinet instantiates a new Cabinet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCabinet(data CabinetData) *Cabinet {
	this := Cabinet{}
	this.Data = data
	return &this
}

// NewCabinetWithDefaults instantiates a new Cabinet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCabinetWithDefaults() *Cabinet {
	this := Cabinet{}
	return &this
}

// GetData returns the Data field value
func (o *Cabinet) GetData() CabinetData {
	if o == nil {
		var ret CabinetData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *Cabinet) GetDataOk() (*CabinetData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *Cabinet) SetData(v CabinetData) {
	o.Data = v
}

func (o Cabinet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Cabinet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *Cabinet) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCabinet := _Cabinet{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCabinet)

	if err != nil {
		return err
	}

	*o = Cabinet(varCabinet)

	return err
}

type NullableCabinet struct {
	value *Cabinet
	isSet bool
}

func (v NullableCabinet) Get() *Cabinet {
	return v.value
}

func (v *NullableCabinet) Set(val *Cabinet) {
	v.value = val
	v.isSet = true
}

func (v NullableCabinet) IsSet() bool {
	return v.isSet
}

func (v *NullableCabinet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCabinet(val *Cabinet) *NullableCabinet {
	return &NullableCabinet{value: val, isSet: true}
}

func (v NullableCabinet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCabinet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


