/*
Chains API

Chains API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOwnProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOwnProfile{}

// CreateOwnProfile struct for CreateOwnProfile
type CreateOwnProfile struct {
	Data CreateOwnProfileData `json:"data"`
}

type _CreateOwnProfile CreateOwnProfile

// NewCreateOwnProfile instantiates a new CreateOwnProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOwnProfile(data CreateOwnProfileData) *CreateOwnProfile {
	this := CreateOwnProfile{}
	this.Data = data
	return &this
}

// NewCreateOwnProfileWithDefaults instantiates a new CreateOwnProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOwnProfileWithDefaults() *CreateOwnProfile {
	this := CreateOwnProfile{}
	return &this
}

// GetData returns the Data field value
func (o *CreateOwnProfile) GetData() CreateOwnProfileData {
	if o == nil {
		var ret CreateOwnProfileData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateOwnProfile) GetDataOk() (*CreateOwnProfileData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateOwnProfile) SetData(v CreateOwnProfileData) {
	o.Data = v
}

func (o CreateOwnProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOwnProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateOwnProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOwnProfile := _CreateOwnProfile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOwnProfile)

	if err != nil {
		return err
	}

	*o = CreateOwnProfile(varCreateOwnProfile)

	return err
}

type NullableCreateOwnProfile struct {
	value *CreateOwnProfile
	isSet bool
}

func (v NullableCreateOwnProfile) Get() *CreateOwnProfile {
	return v.value
}

func (v *NullableCreateOwnProfile) Set(val *CreateOwnProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOwnProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOwnProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOwnProfile(val *CreateOwnProfile) *NullableCreateOwnProfile {
	return &NullableCreateOwnProfile{value: val, isSet: true}
}

func (v NullableCreateOwnProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOwnProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


