/*
Chains API

Chains API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateOwnProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOwnProfile{}

// UpdateOwnProfile struct for UpdateOwnProfile
type UpdateOwnProfile struct {
	Data UpdateOwnProfileData `json:"data"`
}

type _UpdateOwnProfile UpdateOwnProfile

// NewUpdateOwnProfile instantiates a new UpdateOwnProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOwnProfile(data UpdateOwnProfileData) *UpdateOwnProfile {
	this := UpdateOwnProfile{}
	this.Data = data
	return &this
}

// NewUpdateOwnProfileWithDefaults instantiates a new UpdateOwnProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOwnProfileWithDefaults() *UpdateOwnProfile {
	this := UpdateOwnProfile{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateOwnProfile) GetData() UpdateOwnProfileData {
	if o == nil {
		var ret UpdateOwnProfileData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateOwnProfile) GetDataOk() (*UpdateOwnProfileData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateOwnProfile) SetData(v UpdateOwnProfileData) {
	o.Data = v
}

func (o UpdateOwnProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOwnProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateOwnProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOwnProfile := _UpdateOwnProfile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOwnProfile)

	if err != nil {
		return err
	}

	*o = UpdateOwnProfile(varUpdateOwnProfile)

	return err
}

type NullableUpdateOwnProfile struct {
	value *UpdateOwnProfile
	isSet bool
}

func (v NullableUpdateOwnProfile) Get() *UpdateOwnProfile {
	return v.value
}

func (v *NullableUpdateOwnProfile) Set(val *UpdateOwnProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOwnProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOwnProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOwnProfile(val *UpdateOwnProfile) *NullableUpdateOwnProfile {
	return &NullableUpdateOwnProfile{value: val, isSet: true}
}

func (v NullableUpdateOwnProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOwnProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


