openapi: 3.1.1
info:
  title: Cifra SSO REST API
  description: SSO REST API for Cifra app
  version: 0.0.1

paths:
  /chains/auth/v1/own:
    $ref: './paths/sso-svc/OwnData.yaml'

  /re-news/chains/auth/v1/own/refresh:
    $ref: './paths/sso-svc/Refresh.yaml'

  /re-news/chains/auth/v1/own/login:
    $ref: './paths/sso-svc/Login.yaml'

  /re-news/chains/auth/v1/own/callback:
    $ref: './paths/sso-svc/LoginCallback.yaml'

  /re-news/chains/auth/v1/own/logout:
    $ref: './paths/sso-svc/Logout.yaml'

  /re-news/chains/auth/v1/own/sessions:
    $ref: './paths/sso-svc/OwnSessions.yaml'

  /re-news/chains/auth/v1/own/sessions/{session_id}:
    parameters:
      - name: session_id
        in: path
        required: true
        schema:
          type: string
    $ref: './paths/sso-svc/OwnSession.yaml'

    #Admins

  /re-news/chains/auth/v1/admin/{user_id}:
    parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
    $ref: './paths/sso-svc/AdminGetUser.yaml'

  /re-news/chains/auth/v1/admin/{user_id}/{role}:
    parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: role
        in: path
        required: true
        schema:
          type: string
    $ref: './paths/sso-svc/AdminUpdateRole.yaml'

  /re-news/chains/auth/v1/admin/{user_id}/sessions:
    parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
    $ref: './paths/sso-svc/AdminUserSessions.yaml'

  /re-news/chains/auth/v1/admin/{user_id}/sessions/{session_id}:
    parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: session_id
        in: path
        required: true
        schema:
          type: string
    $ref: './paths/sso-svc/AdminUserSession.yaml'

components:
  schemas:

    ########## sso-svc ##########

    # request
    RefreshToken:
      $ref: './spec/components/schemas/sso-svc/requests/RefreshToken.yaml'
    CreateUserByAdmin:
      $ref: './spec/components/schemas/sso-svc/requests/CreateUserByAdmin.yaml'

    # responses
    TokensPair:
      $ref: './spec/components/schemas/sso-svc/responses/TokensPair.yaml'
    AccessToken:
      $ref: './spec/components/schemas/sso-svc/responses/AccessToken.yaml'
    Session:
      $ref: './spec/components/schemas/sso-svc/responses/Session.yaml'
    SessionData:
      $ref: './spec/components/schemas/sso-svc/responses/SessionData.yaml'
    SessionAttributes:
      $ref: './spec/components/schemas/sso-svc/responses/SessionAttributes.yaml'
    SessionsCollection:
      $ref: './spec/components/schemas/sso-svc/responses/SessionsCollection.yaml'
    User:
      $ref: './spec/components/schemas/sso-svc/responses/User.yaml'
    Errors:
      $ref: './spec/components/schemas/Errors.yaml'

    ########## elector-cab ##########

    # request
    UpdateOwnProfile:
      $ref: './spec/components/schemas/elector-cab-svc/requests/UpdateOwnProfile.yaml'
    UpdateProfileByAdmin:
      $ref: './spec/components/schemas/elector-cab-svc/requests/ResetProfileByAdmin.yaml'
    CreateOwnProfile:
      $ref: './spec/components/schemas/elector-cab-svc/requests/CreateOwnProfile.yaml'

    # responses
    Biography:
      $ref: './spec/components/schemas/elector-cab-svc/responses/Biography.yaml'
    BiographyAttributes:
      $ref: './spec/components/schemas/elector-cab-svc/responses/BiographyAttributes.yaml'
    Cabinet:
      $ref: './spec/components/schemas/elector-cab-svc/responses/Cabinet.yaml'
    CabinetAttributes:
      $ref: './spec/components/schemas/elector-cab-svc/responses/CabinetAttributes.yaml'
    Profile:
      $ref: './spec/components/schemas/elector-cab-svc/responses/Profile.yaml'
    ProfileAttributes:
      $ref: './spec/components/schemas/elector-cab-svc/responses/ProfileAttributes.yaml'


  responses:
    Unauthorized:
      $ref: './spec/components/responses/unauthorized.yaml'
    NotFound:
      $ref: './spec/components/responses/notFound.yaml'
    Forbidden:
      $ref: './spec/components/responses/forbidden.yaml'
    Internal:
      $ref: './spec/components/responses/internal.yaml'
    Conflict:
      $ref: './spec/components/responses/conflict.yaml'
    TooManyRequests:
      $ref: './spec/components/responses/tooManyRequests.yaml'
    UnsupportedMediaType:
      $ref: './spec/components/responses/unsupportedMediaType.yaml'
    BadRequest:
      $ref: './spec/components/responses/badRequest.yaml'