openapi: 3.1.1
info:
  title: Chains API
  description: Chains API
  version: 0.0.1

########################################################################################################################
#####                                            SSO-SVC                                                           #####
########################################################################################################################

paths:
  /chains/auth/v1/own:
    $ref: './spec/sso-svc/paths/OwnData.yaml'

  /re-news/chains/auth/v1/own/refresh:
    $ref: './spec/sso-svc/paths/Refresh.yaml'

  /re-news/chains/auth/v1/own/login:
    $ref: './spec/sso-svc/paths/Login.yaml'

  /re-news/chains/auth/v1/own/callback:
    $ref: './spec/sso-svc/paths/LoginCallback.yaml'

  /re-news/chains/auth/v1/own/logout:
    $ref: './spec/sso-svc/paths/Logout.yaml'

  /re-news/chains/auth/v1/own/sessions:
    $ref: './spec/sso-svc/paths/OwnSessions.yaml'

  /re-news/chains/auth/v1/own/sessions/{session_id}:
    parameters:
      - name: session_id
        in: path
        required: true
        schema:
          type: string
    $ref: './spec/sso-svc/paths/OwnSession.yaml'

    #Admins

  /re-news/chains/auth/v1/admin/{user_id}:
    parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
    $ref: './spec/sso-svc/paths/AdminGetUser.yaml'

  /re-news/chains/auth/v1/admin/{user_id}/{role}:
    parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: role
        in: path
        required: true
        schema:
          type: string
    $ref: './spec/sso-svc/paths/AdminUpdateRole.yaml'

  /re-news/chains/auth/v1/admin/{user_id}/sessions:
    parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
    $ref: './spec/sso-svc/paths/AdminUserSessions.yaml'

  /re-news/chains/auth/v1/admin/{user_id}/sessions/{session_id}:
    parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: session_id
        in: path
        required: true
        schema:
          type: string
    $ref: './spec/sso-svc/paths/AdminUserSession.yaml'

components:
  schemas:

    ########## sso-svc ##########

    # request
    RefreshToken:
      $ref: './spec/sso-svc/components/requests/RefreshToken.yaml'
    CreateUserByAdmin:
      $ref: './spec/sso-svc/components/requests/CreateUserByAdmin.yaml'

    # responses
    TokensPair:
      $ref: './spec/sso-svc/components/schemas/TokensPair.yaml'
    AccessToken:
      $ref: './spec/sso-svc/components/schemas/AccessToken.yaml'
    Session:
      $ref: './spec/sso-svc/components/schemas/Session.yaml'
    SessionData:
      $ref: './spec/sso-svc/components/schemas/SessionData.yaml'
    SessionAttributes:
      $ref: './spec/sso-svc/components/schemas/SessionAttributes.yaml'
    SessionsCollection:
      $ref: './spec/sso-svc/components/schemas/SessionsCollection.yaml'
    User:
      $ref: './spec/sso-svc/components/schemas/User.yaml'
    Errors:
      $ref: './spec/common/components/schemas/Errors.yaml'

    ########## elector-cab ##########

    # request
    UpdateOwnProfile:
      $ref: './spec/elector-cab-svc/components/requests/UpdateOwnProfile.yaml'
    UpdateProfileByAdmin:
      $ref: './spec/elector-cab-svc/components/requests/ResetProfileByAdmin.yaml'
    CreateOwnProfile:
      $ref: './spec/elector-cab-svc/components/requests/CreateOwnProfile.yaml'

    # responses
    Biography:
      $ref: './spec/elector-cab-svc/components/schemas/Biography.yaml'
    BiographyAttributes:
      $ref: './spec/elector-cab-svc/components/schemas/BiographyAttributes.yaml'
    Cabinet:
      $ref: './spec/elector-cab-svc/components/schemas/Cabinet.yaml'
    CabinetAttributes:
      $ref: './spec/elector-cab-svc/components/schemas/CabinetAttributes.yaml'
    Profile:
      $ref: './spec/elector-cab-svc/components/schemas/Profile.yaml'
    ProfileAttributes:
      $ref: './spec/elector-cab-svc/components/schemas/ProfileAttributes.yaml'


  responses:
    Internal:
      $ref: './spec/common/components/responses/internalServer.yaml'
    UnsupportedMediaType:
      $ref: './spec/common/components/responses/unsupportedMediaType.yaml'
    BadRequest:
      $ref: './spec/common/components/responses/badRequest.yaml'